NYPL/dxp-react-search

- .travis.yml
- provisioning/deploy
[Jira Ticket](http://jira.nypl.org/browse/RENO-1606)
- Changes TravisCI deployment to use the `after_success` directive instead of `deploy` which may be interfering with build files. This puts it on par with how nypl-d8 is deployed via TravisCI.
May not be able to test until deployed via the `qa` branch.
> RENO-1606 Fix Deployment Builds

- .env.example
- provisioning/set-env
- src/pages/_document.js
- src/utils/analytics.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1657)
- Adds .env.example variable for NEXT_PUBLIC_GA_TRACKING_ID
- Wires up _document.js in Next to render the GA tracking script
- Rough draft of adding the .env variables for GA Tracking ID on QA and PROD to `provisioning/set-env`
> RENO-1657: Setup GA Tracking

- package-lock.json
- package.json
- src/apollo/server/datasources/RefineryApi.js
- src/components/location-finder/Locations/Locations.js
- src/utils/checkAlertsOpenStatus.js
- src/utils/filterByOpenNow.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1677)
- Updates the `filterByOpenNow()` util to use refinery alert data correctly
- Checks for "alert closings" and should ignore "non-closing alerts"
- Updates Location component to display "Location is temporarily closed" status badge.
**Notes on the data returned**
Refinery locations has 92 locations. Around 30 should be "open", the rest are closed.
Location Finder is currently returning 28, which might correct?
> RENO-1677: Open Now Filter Shows Locations That Are Closed

- package-lock.json
- package.json
- src/pages/api/graphql.js
- Fixes `has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
- Allows other domains to access `api/graphql` endpoint
> Fix for CORS Preflight Issue

- CHANGELOG.md
- src/components/location-finder/Locations/Locations.js
- src/components/location-finder/Locations/LocationsPagination.js
- src/hooks/useWindowSize.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1642)
- Adds a custom hook called `useWindowSize()` that calculates the window size of the browser.
- Using this hook, disables pagination for desktop screens by setting the `limit` to get all results instead of 10.
> RENO-1642: Remove Pagination From Desktop

- CHANGELOG.md
- src/components/location-finder/Location/index.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1802)
- Fixed "Today's hours" display to accommodate for hours having "14:45" format and would display the as "2:45pm"
> RENO-1802 - Today's Hours display stripping out minutes

- CHANGELOG.md
- src/components/location-finder/Location/index.js
- src/components/location-finder/Map/index.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1633)
- When map marker is clicked, in addition to scrolling location into view, focus is added to the location link.
- Updated location heading IDs to be prefixed with `lid-` since IDs should not start with numbers (i.e, 96th-street, 125th-street, etc)
> RENO-1633: Add Focus to Location Anchor When Map Marker is Clicked

- CHANGELOG.md
- package-lock.json
- package.json
- src/apollo/server/datasources/RefineryApi.js
- src/utils/checkAlertsOpenStatus.js
- src/utils/checkAlertsOpenStatus.test.js
- src/utils/filterByOpenNow.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1830)
- Accommodate hours and mins in closing logic related to alerts/closings for all day closings.
- Removed `date-fns` and `date-fns-tz` packages.
- Adds `DayJS` package for handling and comparing dates.
- Refactors `checkAlertsOpenStatus()` util function to be testable and use `DayJS` for date comparisons.
- Adds unit tests for `checkAlertsOpenStatus()` util function
> RENO-1830: All Day Closings Accommodate Hours + Mins

- package-lock.json
- package.json
- src/apollo/client/withApollo.js
- src/components/location-finder/Locations/Locations.js
- src/components/location-finder/Locations/LocationsPagination.js
- src/components/location-finder/Map/index.js
- src/components/location-finder/SearchAutoSuggest/SearchAutoSuggest.js
- src/components/location-finder/SearchForm/SearchForm.js
- src/pages/locations/index.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-1937)
- Upgrades to Apollo Client 3 (now uses @apollo/client) (Read more here: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/)
- Removes the following modules not needed with `@apollo/client`
- @apollo/react-hooks
- @apollo/react-ssr
- apollo-cache-inmemory
- apollo-client
- apollo-link-http
- Fixed duplicate render issue caused by apollo client 3.
> RENO-1937: Upgrade/Migrate to Apollo Client v3

- Dockerfile
[Jira Ticket](http://jira.nypl.org/browse/RENO-2110)
- Sets the timezone for Docker container/server.
> Set timezone for docker container to america/new_york

- src/apollo/server/resolvers/locationResolver.js
- src/apollo/server/type-defs.js
- src/components/location-finder/Location/Location.js
- src/components/location-finder/Location/Location.scss
- src/components/location-finder/Location/LocationHours.js
- src/components/location-finder/Location/LocationHours.test.js
- src/components/location-finder/Locations/Locations.gql
- testHelper/__mocks/allLocations.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-2108)
- Adds "by appointment only" notice message for Divisions that have by appointment only hours. Currently, only "DeWitt Wallace Periodical Room" has this data, and related notice.
> RENO-2108: Wire Up Division By Appointment Only Field

- src/components/location-finder/SearchFilters/FiltersButton.js
- src/components/location-finder/SearchFilters/SearchFilters.scss
[Jira Ticket](http://jira.nypl.org/browse/RENO-2115)
- For mobile only, Filters button now has a count of the number of selected items.
> RENO-2115: Adds Selected Items Count to Mobile Filters Button

- package-lock.json
- package.json
- src/apollo/client/queries/Locations.gql
- src/apollo/server/resolvers/locationResolver.js
- src/apollo/server/type-defs.js
- src/components/location-finder/Locations/Locations.js
- src/components/location-finder/Locations/Locations.test.js
- src/components/location-finder/Map/Map.js
- src/components/location-finder/SearchForm/SearchForm.js
- src/utils/sortByDistance.js
- src/utils/sortByDistance.test.js
[Jira Ticket](http://jira.nypl.org/browse/RENO-2120)
- Since Divisions and Centers have the same address as their parent Locations, these locations were not appearing at the top of the search results list. This PR adds functionality to ensure that if someone searches for a division such as "Dewitt", for example, it will appear as the top result, over "SASB" (parent location).
> RENO-2120: Improvements for Sort By Distance to Include Location Name

- src/apollo/server/resolvers/autoSuggestionsResolver.js
- src/apollo/server/resolvers/searchResolver.js
- src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-2309)
- Removes html entities from title field (this is a temp workaround, as this should really happen on the Drupal side)
- Changes OnlineResourceCard description field to render as html
- Preview Env: https://pr149-owtxo5pjjmxbdqyqppmshs3iixtd7hsf.tugboat.qa/research/collections/online-resources
> RENO-2309: Remove HYML Entities From Title Field + Render Description as HTML

- src/apollo/client/queries/LocationMatchesByIp.gql
- src/apollo/server/type-defs/search.js
- src/components/online-resources/OnlineResourceCard/OnlineResourceCardHeading.js
- src/pages/research/collections/articles-databases/[slug].js
[Jira Ticket](https://jira.nypl.org/browse/RENO-2407)
- Wires up the detail pages to use ip address to determine if a plain text heading or link is displayed
> RENO-2407: Database Title Should Appear as a Link For Some IP Addresses

- src/components/ds-prototypes/MultiSelect/MultiSelect.js
- src/components/online-resources/SearchForm/SearchFilters.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-2336)
- Fixes bug where unchecking a multiselect item and saving filters will still return 1 for selected items. See jira ticket for acceptance criteria.
> RENO-2336: MultiSelect Filter Does Not Deselect After Unchecking Checkbox

- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/components/shared/ContentComponents/TextWithImage.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-2776)
- In Drupal 9 backend, the "Text With Image" component does not require an image to be added. This was causing a bug on the frontend, where the React component expected there to always be an image. So the work here checks if there is an image, and if not, will skip rendering that portion of the component. Example of bug on QA:
https://qa-scout.nypl.org/blog/2022/03/01/qa-blog-reno-2680?preview_secret=o934Ysf3Hpu3irVXFBYvGCAyHjU3F&uuid=8d885904-0553-4073-b82d-2da729c94338&revision_id=34638
```
NEXT_PUBLIC_DRUPAL_PREVIEW_SECRET=o934Ysf3Hpu3irVXFBYvGCAyHjU3F
DRUPAL_CONSUMER_UUID=7af062d8-1b9d-4d81-81b7-a4f681a651d4
DRUPAL_CONSUMER_SECRET=test1234
```
> RENO-2776: Bug Fix for Text with Image Component, Image Field Not Required

- cypress.json
- cypress/tests/blogs/blogs-all.test.js
- cypress/tests/blogs/blogs-main.test.js
- src/apollo/server/type-defs/blog.js
- src/components/blogs/BlogsContainer/BlogsContainer.tsx
- src/components/shared/FilterBar/FilterBar.tsx
- src/pages/blog/all.tsx
- src/pages/blog/index.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-2793)
- Fixes bug where filter bar was not reseting pagination to page 1
- Fixes bug where unpublished blog posts were throwing off page count and pagination, by adding `status`, so only published blog posts are specifically queries for.
- First draft of Blogs all pg tests
> RENO-2793: Pagination Bug Fixes

- src/__content/blogs.js
- src/components/blogs/layouts/PageContainer.js
- src/pages/blog/all.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-2806)
- Updates breadcrumbs and cta to use "Blog" instead of "Blogs"
> RENO-2806: Update Breadcrumbs to Use Blog Singular

- src/components/location-finder/Location/Location.tsx
- src/components/location-finder/Location/LocationAccessibility.test.js
- src/components/location-finder/Location/LocationAccessibility.tsx
- src/components/location-finder/Location/LocationHours.tsx
- src/pages/locations/index.tsx
- src/utils/config.js
[Jira Ticket](https://jira.nypl.org/browseRENO-2790)
- change location address to be multi-line
- change parent library to italic
- set hours to bold 
- fix layout of  "* Division is by appointment only."
- add /Locations to breadcrumb
> Reno 2717/location finder fixes

- cypress/tests/articles-databases/articles-databases.test.js
- src/__content/onlineResources.js
- src/components/online-resources/AlphabetNav/AlphabetNav.module.css
- src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
- src/components/online-resources/OnlineResourceCard/OnlineResourceCard.module.css
- src/components/online-resources/layouts/PageContainer.js
- src/pages/research/collections/articles-databases/[slug].js
- src/pages/research/collections/articles-databases/featured/[slug].js
- src/pages/research/collections/articles-databases/find-journals-title-databases.tsx
- src/pages/research/collections/articles-databases/search.js
- src/pages/research/collections/articles-databases/verify.js
Compare to [Live site]( https://www.nypl.org/research/collections/articles-databases): 
- Update A-Z Nav font size from 16px to 18px (as per live page)
- Replace <a> tag with <Link> to add underline for Access Locations details (click “Full Details” button to see this)
- Correct color for "CORE RESOURCE" tag. See: `http://localhost:3000/research/collections/articles-databases/search?q=S%26P+Capital+IQ&subject=62&page=1`
- Update breadcrumbs with current page
> Reno 2791/articles databases fixes

- cypress/tests/articles-databases/articles-databases-main.test.js
- cypress/tests/articles-databases/articles-databases.test.js
- cypress/tests/blogs/blog-post.test.js
- src/pages/404.tsx
- src/pages/_error.tsx
- src/pages/blog/[...slug].tsx
- src/pages/research/collections/articles-databases/[slug].js
- src/pages/research/collections/articles-databases/featured/[slug].js
[Jira Ticket](https://jira.nypl.org/browse/RENO-2742)
- Adds a basic 404 page to Scout, replacing the NextJS default. This is setup for slug pages which use Drupal CMS for routing, as well as routes that only exist in NextJS.
> RENO-2742: Add 404 Pg

- src/components/shared/ContentComponents/CardList.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-2824)
- Adjusts `CardList` to align items `flex-start` not `center` to position image at top text block.
> RENO-2824: CardList Change Image Alignment to Top

- src/apollo/client/fragments/blogFields.js
- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/apollo/server/type-defs/shared.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-2834)
- Wires up heading and description to Audio component, which were left off previously by mistake.
> RENO-2834: Wire up audio heading and desc fields

- cypress/tests/blogs/blogs-all.test.js
- src/components/blogs/BlogsContainer/BlogsContainer.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-2840)
- Fixes bug where channel filter does not get updated properly when selecting next pg. 
- Adds test for this scenario
**To reproduce bug**
- go here: https://qa-www.nypl.org/blog/all?channel=730&page=1
- Click "next" pg link in pagination 
- Query parms change to `?alpha=730&page=2`
> RENO-2840: Fix Typo in Channel Filter Pagination

- src/pages/_document.js
- Adds logic to use the `qa-header.nypl` remote script based on env variable.
> RENO-2942: Make Header Embed Script Env Aware

- src/apollo/server/resolvers/homePageResolver.js
- src/apollo/server/type-defs/homepage.js
- src/pages/home/index.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3071)
- Updates drupal Resolver for Updates section (section 8)
- Updates QraphQL query with Updates section
- Replaces mock content for Updates section with data from Drupal
> RENO-3071: Connect Updates Section with Drupal Content

- src/components/home-v1/EventCollection/EventCollection.tsx
- src/components/home-v1/EventCollection/EventCollectionTabPanelContent.tsx
- src/components/home-v1/theme/event.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3095)
- Fixes font size of event card for mobile and tablet view
- Adjusts spacing between card according to live home page
> Reno 3095/fix events collection mobile card style

- src/apollo/server/resolvers/pressReleaseResolver.js
- src/apollo/server/type-defs/press.js
- src/apollo/withApollo/apollo.ts
- src/components/press-releases/PressRelease/PressRelease.tsx
- src/components/press-releases/PressReleaseCollection/PressReleaseCollection.tsx
- src/components/press-releases/PressReleaseCollection/index.ts
- src/pages/press/[...slug].tsx
- src/pages/press/index.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3081)
- Updates press page index.tsx file with next's getStaticProps 
- Updates query in PressReleaseCollection.tsx to filter by status
- Creates PressFilter type for query
- Updates [...slug].tsx with next's getServerSideProps
> RENO-3081: Update Press Pages With getServerSideProps

- src/apollo/server/resolvers/homePageResolver.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-3153)
- Updates Home page event to use `field_ts_heading` instead of `title`
> RENO-3153: Update HomePageEvent to Use Heading Field

- src/components/home-v1/EventCollection/EventCollection.tsx
- src/components/home-v1/Spotlight/Spotlight.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3166)
- Hide "Spotlight" and "What's On" sections if no items.
> RENO-3166: Hide spotlight and event collections if no items

- src/components/home-v1/Slideshow/Slideshow.tsx
- src/components/home-v1/Slideshow/SlideshowContainer.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3170)
- Adds a check for the length of the incoming items in Slideshow.tsx
- Crops the incoming items at 10 items if needed
> RENO-3170: Update Slideshow To Cap Items Array

- src/apollo/client/fragments/pressFields.js
- src/apollo/server/resolvers/pressReleaseResolver.js
- src/apollo/server/type-defs/press.js
- src/components/press-releases/PressRelease/PressRelease.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3087)
- Adds `field_tfls_subtitle` to the pressReleaseResolver
- Adds subtitle to the press type
- Adds subtitle to the pressFields
- Replaces description with subtitle in PressRelease.tsx
> RENO-3087: Wire Up Subtitle and Meta Description Fields to individual PressRelease

- .travis.yml
- .vercel/ignored-build-step.sh
- provisioning/set-env
- Update `.travis.yml` to build on `development` and `sandbox` branches.
- Update `set-env` bash script to set Scout environment variables for `development` and `sandbox`
- Update vercel ignored build step script to skip builds for `development` or `sandbox`
> RENO-3301: Setup Additional AWS environments

- src/pages/_error.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3309)
- Remove off-screen transition on Lion logo when at the xl screen size
- Convert back to home action from a Button to a Link
> RENO-3309: Maintenance page style adjustments

- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/apollo/server/type-defs/shared.js
- src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
- src/components/shared/EmailSubscription/EmailSubscription.tsx
- src/components/shared/EmailSubscription/EmailSubscriptionForm.tsx
- src/pages/api/salesforce.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3367)
- Adds the Drupal sourceCode field to the EmailSubscription graphQL query
- Appends the data to the request body for the salesforce api call
- Updates the formHelperText with the link to privacy and policy
> RENO-3367: Add Source Code Field To EmailSubscription Query

- src/components/shared/EmailSubscription/EmailSubscription.tsx
- src/components/shared/EmailSubscription/EmailSubscriptionConfirmation.tsx
- src/components/shared/EmailSubscription/EmailSubscriptionForm.tsx
- src/components/shared/EmailSubscription/EmailSubscriptionWrapper.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3384)
- Updates Success confirmation message with the text provided by comms
- Updates the privacy policy disclaimer with the text provided by comms
- Updates the privacy text to include the link to NYPL privacy policy - if clicked the link will open in a new tab
- Updates the min height of the EmailSubscription Wrapper to match [Figma designs](https://www.figma.com/file/HhtAEYL9QFZ6PPXTu75T0H/Newsletter-Component?node-id=1619%3A28678&t=jDBlzBLnhW7SI0dI-0)
- Adds isRequired prop to the EmailSubscription TextInput
> Reno 3384: Update Success and Privacy Disclaimer Message

- src/components/home-v1/CardGrid/CardGrid.test.tsx
- src/components/home-v1/CardGrid/__snapshots__/CardGrid.test.tsx.snap
- src/components/home-v1/ComponentWrapper/ComponentWrapper.tsx
- src/components/home-v1/Slideshow/__snapshots__/Slideshow.test.tsx.snap
[Jira Ticket](https://jira.nypl.org/browse/RENO-3378)
- Checks on the ComponentWrapper level if the seeMore button object contains a button text
- Conditionally renders the See More button only when button text was passed from Drupal
- Updates tests for Slideshow and CardGrid
> RENO-3378: Fix seeMore Button

- src/utils/get-colorway.test.ts
- src/utils/get-colorway.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3435)
- Adds logic to sanitize slug strings
- Updates get-colorway tests
-> If Sideshow tests are failing run `npm install` to ensure the correct version of `testing-library/user-event` is installed
> RENO-3435: Add String Sanitization To GetColorway

- src/apollo/with-drupal-router.test.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-3439)
- Adds bundle property to `decoupledRouterDataMock`
*Note: If Slideshow tests are failing run `npm i` to get the required version of `testing-library/user-event`
> RENO-3439: Fix Console Error For with-drupal-router test

- src/apollo/server/datasources/DrupalApi.js
- src/apollo/server/datasources/drupal-json-api/DrupalJsonApi.ts
- src/apollo/server/type-defs/decoupledRouter.js
- src/apollo/with-drupal-router.test.js
- src/apollo/with-drupal-router.ts
- src/hooks/useDecoupledRouter.ts
- src/pages/api/preview.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3451)
- Adds `isPreview` prop  to getDecoupledRouter to catch and handle preview request
- Removes unused getDecoupledRouter function from DrupalJsonApi.ts
- Updates withDrupalRouter to handle preview requests
- Updates withDrupalRouter preview test 
* Note: Cypress text for next/prev page in /press is broken as of 03/23
> RENO-3451: Fix SectionFront Preview

- .vscode/settings.json
- src/apollo/server/datasources/drupal-json-api/DrupalJsonApi.ts
- src/apollo/server/type-defs/shared.js
- src/apollo/with-drupal-router.ts
- src/components/shared/Link/NextChakraLink.tsx
- src/components/shared/Link/NextDsLink.tsx
- src/hooks/useDecoupledRouter.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3507)
- Adds isPreview to the query in useDecoupledRouter
- Fixes some formatting
- Updates the props in NextsLink to fix *NextLink prop deprecated* message
> RENO-3507: Fix useDecoupledRouter Query

- src/apollo/server/resolvers/sectionFrontResolver.js
- src/apollo/server/type-defs/sectionFront.js
- src/apollo/server/type-defs/shared.js
- src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3536)
- Adds schema type for breadcrumbs
- Adds breadcrumbs to sectionfront resolver
- Passes sectionFront.breadcrumbs.data to page container component
**Backend**
https://pr1057-nypl1.pantheonsite.io
**Frontend**
https://scout-git-reno-3536-wire-up-breadcrumb-data-nypl.vercel.app
> RENO-3536: Wires Up Breadcrumbs from Drupal JSON API.

- src/apollo/server/resolvers/sectionFrontResolver.js
- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/apollo/server/type-defs/shared.js
- src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
- src/components/shared/ContentComponents/getReactComponent.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3550)
> RENO-3550: Remove status field and related code

- cypress/support/utils/testSearch.ts
- src/utils/get-colorway.test.ts
- src/utils/get-colorway.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3537)
[Colorway List](https://docs.google.com/spreadsheets/d/1mlN7_XhB3Oc4XvU2kBaRYkco3KtnjtqjjpRgTC3vyjg/edit#gid=0)
- Adds remaining colorway values to lookup table
- Uses nypl color values where possible
- Updates colorway tests 
Test colorways of all available section front pages:
* use qa-drupal data
> RENO-3537: Add Remaining Colorways

- src/apollo/server/resolvers/sectionFrontResolver.js
- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/apollo/server/type-defs/shared.js
- src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx
- src/components/shared/ButtonLink/ButtonLink.tsx
- src/components/shared/ButtonLink/index.ts
- src/components/shared/CardGrid/Card.tsx
- src/components/shared/CardGrid/CardGrid.tsx
- src/components/shared/ContentComponents/ButtonLinks.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3546)
[Figma Design](https://www.figma.com/file/Yo3bXT18Lz7946ixcEtte9/RENO-Section-Fronts?type=design&node-id=4310-71278)
- Adds button links to Card component.
- See https://github.com/NYPL/nypl-d8/pull/1061 for the D9 backend part of this work.
> RENO-3546: Add Button Links to Card Component

- src/components/shared/FilterBar/FilterBar.tsx
- src/pages/_app.tsx
- src/utils/get-site-section.ts
- src/utils/submit-adobe-page-view.ts
[Jira Ticket](https://jira.nypl.org/browse/RENO-3625)
- Updates props for submit-adobe-page-view 
- Adds logic for new page_name values
- Updates the dependency array in FilterBar.tsx to fix lag in query params on router
> RENO-3625: AA Update Page Name

- src/apollo/server/resolvers/drupal-types.ts
- src/apollo/server/resolvers/page-resolver.ts
- src/apollo/server/type-defs/page.ts
- src/components/pages/Page.tsx
- src/components/shared/DonorCredit/__snapshots__/DonorCredit.test.tsx.snap
[Jira Ticket](https://jira.nypl.org/browse/RENO-3773)
- Updates page schema with breadcrumbs
- Updates page resolver with breadcrumbs
- Adds `DrupalJsonApiBreadcrumbItem` type to `drupal-types.ts`
- Adds breadcrumbs to `PAGE_QUERY`
- Updates Page component with breadcrumbs
> RENO-3773: Setup Breadcrumbs for Pages

- src/apollo/client/fragments/blogFields.js
- src/apollo/client/fragments/pressFields.js
- src/apollo/server/resolvers/drupal-paragraphs/text-with-image-resolver.ts
- src/apollo/server/type-defs/page.ts
- src/apollo/server/type-defs/shared.js
- src/components/blogs/BlogPost/BlogPost.tsx
- src/components/pages/Page.tsx
- src/components/shared/ContentComponents/TextWithImage.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3786)
- Adds `imageAlignment` to TextWithImage schema and resolver
- Adds `imageAlignment` to TextWithImage Component
- Adds `imageAlignment` to Page, Blog and Press query
- Adds TextWithImage to BlogPost.tsx
> RENO-3786: Extend TextWithImage Component

- next.config.js
[Jira Ticket](https://jira.nypl.org/browse/RENO-3796)
- Add contentcafe12.btol.com to next.config.js image source whitelist.
> RENO-3796: Allow contentcafe12.btol.com as Image Source

- src/apollo/client/fragments/blogFields.js
- src/apollo/client/fragments/pressFields.js
- src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
- src/apollo/server/type-defs/shared.js
- src/components/shared/ContentComponents/ImageComponent.tsx
- src/components/shared/ContentComponents/TextWithImage.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3735)
- Adds link data to `TextWithImage` schema, resolver and query
- Adds link prop to `TextWithImage` component
- Exports `WithLink` component from `ImageComponent` to be used in `TextWithImage` component
> RENO-3735: Add image source link to TextWithImage

- package-lock.json
- package.json
- src/apollo/server/resolvers/drupal-paragraphs/image-resolver.ts
- src/apollo/server/resolvers/drupal-paragraphs/text-with-image-resolver.ts
- src/apollo/server/type-defs/shared.js
- src/components/pages/Page.tsx
[Jira Ticket](https://jira.nypl.org/browse/RENO-3735)
- Adds link to new `TextWithImage` resolver
- Adds link to `TextWithImage` schema to avoid error
- Adds `link` to Page component query
- Upgrades `nypl/design-system-react-components` to version 2.1.2 - this fixes the Hero bg 
```
if (imageAlignment === null) {
imageAlignment = "left";
}
``` 
to the TextWithImage component.
_There changes will only show the following if [PR 465](https://github.com/NYPL/dxp-react-search/pull/465) was previously merged to development and this basic-pages-epic and this branch were updated with those changes_
> RENO-3735: Update TextWithImage with image source link
