NYPL/dxp-react-search

package.json
src/components/location-finder/RightRail/RightRail.scss
src/components/location-finder/RightRail/content.js
src/components/location-finder/RightRail/index.js
src/pages/location-finder/index.js
src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1549)
[Metronome](http://themetronome.co/components/mn-75-right-rail/?fresh=true)
- Pull in latest code
- Run "npm install" as the version of design system react components is updated

RENO-1549: Location Finder: Build "Right Rail" Component

---

src/components/location-finder/BottomPromo/BottomPromo.scss
src/components/location-finder/BottomPromo/content.js
src/components/location-finder/BottomPromo/index.js
src/pages/location-finder/index.js
src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1551)
[Metronome](http://themetronome.co/components/op-321-promo-50-split-item/?fresh=true)
- Setup the bottom promo components

RENO-1551 - build bottom promo components

---

src/components/location-finder/Location/Location.scss
src/components/location-finder/Location/index.js
src/components/location-finder/Locations/Locations.scss
src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1572)
- Adds Accessibility icons to the location component.

RENO-1572 - Location component accessibility icons

---

src/apollo/server/datasources/DrupalApi.js
src/apollo/server/datasources/RefineryApi.js
src/apollo/server/type-defs.js
src/components/location-finder/Location/Location.scss
src/components/location-finder/Location/index.js
src/components/location-finder/Locations/Locations.gql

RENO-1557:  Location Finder: Location Component Hours

---

src/components/location-finder/Location/Location.scss
src/components/location-finder/Location/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1581)
- Adds Accessibility Note if it's not empty

RENO-1581 - Location Component Accessibility Note

---

src/components/location-finder/Location/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1573)
- Sets up a Get Directions link to Google Maps for each Location
- Adds spaces between the location links

RENO-1573: Get Directions Google Maps Link

---

src/apollo/server/datasources/RefineryApi.js
src/apollo/server/type-defs.js
src/components/location-finder/Locations/Locations.gql
src/components/location-finder/Locations/Locations.js
src/components/location-finder/Locations/Locations.scss
src/components/location-finder/Map/Locations.gql
src/components/location-finder/Map/index.js
src/components/location-finder/SearchForm/index.js
src/components/location-finder/SearchResultsDetails/index.js
src/redux/actions/index.js
src/redux/reducers/search.js
src/utils/filterByOpenNow.js
src/utils/sortByName.js

RENO-1559: Open Now Checkbox

---

src/components/location-finder/BottomPromo/BottomPromo.scss
src/components/location-finder/Locations/Locations.scss
src/components/location-finder/RightRail/RightRail.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1586)
- Updates BottomPromo and RightRail components to use breakpoint mixin from breakpoints-sass.  An entry in Locations component was updated as well.

RENO-1586 - Update Breakpoints for components

---

src/components/location-finder/Hero/Hero.scss
src/components/location-finder/Hero/content.js
src/components/location-finder/Hero/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1601)
- Updated hero text.  New text also includes link, so the link color was changed to white for accessibility.

RENO-1601 - Update hero text

---

src/components/location-finder/BottomPromo/BottomPromo.scss
src/components/location-finder/BottomPromo/content.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1602)
- Updated content

RENO-1602 - Update content for Midtown Campus component

---

src/components/location-finder/Location/Location.scss
src/components/location-finder/Location/LocationDistance.js
src/components/location-finder/Location/index.js
src/components/location-finder/SearchForm/index.js
src/utils/googleGeocode.js

Location Component tweaks

---

src/components/location-finder/BottomPromo/BottomPromo.scss
src/components/location-finder/Location/Location.scss
src/components/location-finder/Location/index.js
src/components/location-finder/RightRail/RightRail.scss
src/components/location-finder/SearchForm/SearchForm.scss
src/components/location-finder/SearchHeader/SearchHeader.scss
src/components/location-finder/SearchHeader/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1618)
- Includes fixes from the following Jira tickets:
https://jira.nypl.org/browse/RENO-1618
https://jira.nypl.org/browse/RENO-1619
https://jira.nypl.org/browse/RENO-1621
https://jira.nypl.org/browse/RENO-1623
https://jira.nypl.org/browse/RENO-1624
https://jira.nypl.org/browse/RENO-1626
https://jira.nypl.org/browse/RENO-1628
https://jira.nypl.org/browse/RENO-1629

RENO-1618 - Location Finder VQA

---

next.config.js
package-lock.json
package.json
src/components/location-finder/SearchForm/SearchForm.scss

RENO-1595: Fix Major IE11 Bugs (Simplified)

---

src/components/location-finder/Meta/Meta.js
src/components/location-finder/Meta/index.js
src/pages/location-finder/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1616)
- Sets up a Meta component
- Adds the metatags specified in the ticket to the 'next/head' <Head> component

RENO-1616: Metatags

---

src/components/location-finder/Hero/Hero.scss
src/components/location-finder/Locations/Locations.scss
src/components/location-finder/RightRail/RightRail.scss
src/components/location-finder/SearchHeader/SearchHeader.scss
src/styles/base/_mixins.scss
src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1640)
- Attempts to better align page elements due to edge spacing issues with breakout/wrapper mixins from DS

RENO-1640: Edge spacing and alignment issues

---

src/components/location-finder/SearchForm/SearchAutoSuggest.scss
src/components/location-finder/SearchForm/SearchForm.scss

- RENO-1620 - hover and unhover state of search bar
- RENO-1627 - search button should be on the same line as search bar in smaller viewpoints
- RENO-1631 - left align 'open now' (med viewpoint)

RENO-16XX - Location Finder VQA

---

src/components/location-finder/SearchForm/index.js

RENO-1649: Adds aria-label to search bar input

---

src/components/location-finder/Location/Location.scss
src/components/location-finder/Locations/Locations.scss
src/styles/base/_mixins.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1641)
- Slight adjustment to the padding on the location status callout
- Adjustment to width and color of scrollbar

RENO 1641-1634 Location Finder VQA

---

src/components/location-finder/SearchResultsDetails/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1680)
- Changes the search results message

RENO-1680 - Tweak search results message

---

src/components/location-finder/BottomPromo/BottomPromo.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1626)
- Changes the strategy for the background color for the Bottom Promos
- Adjusts the Bottom Promo spacing across breakpoints

RENO-1626: Adjust bottom promo background and spacing

---

src/components/location-finder/Locations/Locations.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1679)
- Increases the padding between the results map and bottom promo element

RENO-1679 - Location Finder - increase padding below map

---

src/components/location-finder/SearchAutoSuggest/SearchAutoSuggest.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1676)
- Sets the highlightFirstSuggestion to false so that when enter/return key is pressed, it searches for the term entered and doesn't select the first result.

RENO-1676 - Location Finder - search entered keyword by hitting enter/return key

---

src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1689)
- Quick fix to remove extra whitespace from footer

RENO-1689: Remove white space from Footer bottom

---

src/components/location-finder/Locations/Locations.js
src/components/location-finder/Locations/Locations.scss
src/pages/locations/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1625)
-

RENO-1625: Search Results Details Align Top of Map

---

CHANGELOG.md
src/components/location-finder/Location/Location.scss
src/components/location-finder/Locations/Locations.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1703)
- Fixes the outline left border not being visible when "View on Map" is clicked.

RENO-1703 - Box around "View on Map" Cut Off

---

CHANGELOG.md
src/components/location-finder/Locations/Locations.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1721)
-

RENO-1721: Clear Search Terms Display on Own Line on Mobile

---

CHANGELOG.md
src/components/location-finder/SearchResultsDetails/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1731)
-

RENO-1731: Adds role alert to search-results-details div

---

src/components/location-finder/SearchResultsDetails/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1746)
- Adds a period after "Clear all search terms"

RENO-1746 - Clear all search terms (needs a period after)

---

CHANGELOG.md
src/components/location-finder/SearchForm/SearchForm.gql
src/components/location-finder/SearchForm/SearchForm.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1747)
-

RENO-1747: Search by Library First Name

---

CHANGELOG.md
src/components/location-finder/Location/index.js

- Changes the close message from "no hours available" to "closed"

RENO-1719 - Changed closed message

---

CHANGELOG.md
src/components/location-finder/Location/index.js
src/components/location-finder/Locations/Locations.scss
src/components/location-finder/Map/index.js
src/pages/locations/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1741)
- Clicking on "View on Map" scrolls the page down to the map on mobile sizes.
- Adds a "Back to List" link below the map that will scroll the page back up to the location list

RENO-1741 - Mobile "View on Map" Fix

---

CHANGELOG.md
src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1751)
- Removes horizontal scroll bar.

RENO-1751 - Horizontal Scroll bar

---

CHANGELOG.md
src/components/location-finder/Map/index.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1633)
- On Desktop only, when map markers are clicked, the location list with scroll to the location clicked.

RENO-1633: Map Markers on Click Should Scroll to Location

---

CHANGELOG.md
src/components/location-finder/Location/LocationHours.test.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1827)
- Add test coverage for `LocationHours` component.

RENO-1827: Adds Tests for LocationHours Component

---

CHANGELOG.md
src/components/location-finder/Location/LocationAccessibility.test.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1828)
- Creates 3 tests for rendering the component based on accessibility status

RENO-1828 - Location Finder: Write Tests for LocationAccessibility Component

---

src/apollo/server/datasources/RefineryApi.js
src/utils/checkAlertsOpenStatus.test.js
src/utils/filterByOpenNow.js
src/utils/hasActiveClosing.js
src/utils/hasActiveClosing.test.js
src/utils/naturalSort.js
src/utils/naturalSort.test.js
src/utils/setTodaysHours.js
src/utils/setTodaysHours.test.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1775)
- Adds better timezone handling to `refineryApi` datasource.
- Renames util function `checkAlertsOpenStatus()` to `hasActiveClosing()`
- Adds test coverage for `hasActiveClosing()`
- Adds `naturalSort()` and related tests
- Adds `setTodaysHours()` util function and related tests

RENO-1775: Handle late openings and early closings

---

CHANGELOG.md
package-lock.json
package.json

Lock NextJS to 9.5.5 

---

CHANGELOG.md
package-lock.json
package.json

RENO-1705: Upgraded DXP React Footer 0.5.7 -> 0.5.8

---

src/apollo/server/datasources/RefineryApi.js
src/utils/filterByOpenNow.js
src/utils/hasActiveClosing.js
src/utils/hasActiveClosing.test.js
src/utils/setTodaysHours.test.js

RENO-1775: Hotfix for Late Openings Not Modifying Hours

---

next.config.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-1947)
- Adds conditional for `ASSET_PREFIX` to fix broken builds on Vercel.

Small Changes for Vercel Preview Envs

---

CHANGELOG.md
vercel.sh

Skip Builds for qa and production branches on Vercel

---

package-lock.json
package.json
src/components/location-finder/SearchFilters/CheckboxList.js
src/components/location-finder/SearchFilters/DropdownDesktop.js
src/components/location-finder/SearchFilters/DropdownMobile.js
src/components/location-finder/SearchFilters/DropdownMobileButtons.js
src/components/location-finder/SearchFilters/SearchFilters.js
src/components/location-finder/SearchFilters/SearchFiltersContext.js
src/components/location-finder/SearchFilters/SearchFiltersUtils.js

Filters Use Context for Shared State

---

package-lock.json
src/components/location-finder/Location/LocationHours.js
src/components/location-finder/SearchFilters/SearchFilters.scss

Location Finder Project QA Bug Fixes

---

src/apollo/server/resolvers/locationResolver.js
src/apollo/server/type-defs.js
src/components/location-finder/Locations/Locations.gql
testHelper/__mocks/allLocations.js

RENO-2110:

---

src/apollo/server/datasources/RefineryApi.js
src/apollo/server/resolvers/termResolver.js
src/utils/getSubjectsAllowList.js

[Jira Ticket](http://jira.nypl.org/browse/RENO-2106)
- For Subjects filters only, used an allowList of terms pulled from Divisions endpoints to filter out subject terms not associated with Divisions.

RENO-2106: Subject Allow List Terms

---

src/apollo/client/queries/Locations.gql
src/components/location-finder/Locations/Locations.js
src/components/location-finder/Map/Map.js
src/components/location-finder/SearchAutoSuggest/SearchAutoSuggest.js
src/components/location-finder/SearchForm/SearchForm.js
src/components/shared/layouts/Main.js

RENO-2104: Performance Improvements

---

src/components/location-finder/SearchFilters/DropdownMobile.js
src/components/location-finder/SearchFilters/DropdownMobileButtons.js
src/components/location-finder/SearchFilters/DropdownMobileClear.js
src/components/location-finder/SearchFilters/FiltersButton.js
src/components/location-finder/SearchFilters/SearchFilters.js
src/components/location-finder/SearchFilters/SearchFilters.scss
src/components/location-finder/SearchFilters/SearchFiltersContext.js

[RENO-2114](https://jira.nypl.org/browse/RENO-2114)
[RENO-2117](https://jira.nypl.org/browse/RENO-2117)
- Various Fixes for Mobile Filters

RENO-2114+2117: Various Changes for Mobile Filters

---

src/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-2124)
-

RENO-2124: Fix for Global Alerts Links Colors

---

README.md
package-lock.json
package.json
src/components/location-finder/Location/LocationHours.js
src/components/location-finder/SearchFilters/SearchFilters.scss
src/components/location-finder/SearchForm/SearchForm.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-2138)
- Fixes small bug with the layout of Search Filters on iPad width.

RENO-2138: Location Finder: iPad Width Layout Bug

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
src/components/shared/Dropdown/Dropdown.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-2112)
- Changes the border color for a filter with options selected to #000000

RENO-2112 - Border color for filters with option(s) selected

---

src/components/location-finder/SearchFilters/CheckboxList.js
src/components/location-finder/SearchFilters/SearchFilters.scss
src/components/location-finder/SearchForm/SearchForm.scss

[Jira Ticket](https://jira.nypl.org/browse/RENO-2113)
- Bold parent subjects and adds4 pixels padding between each set of subjects

RENO-2113 - Subject Specialities (bold and more padding)

---

src/components/ds-prototypes/AutoSuggest/AutoSuggest.js
src/components/location-finder/Location/Location.test.js
src/components/location-finder/Locations/Locations.test.js
src/components/location-finder/SearchForm/SearchForm.js
src/components/location-finder/SearchForm/SearchForm.scss
src/components/location-finder/SearchHeader/SearchHeader.js
src/components/location-finder/SearchHeader/SearchHeader.test.js
src/components/online-resources/SearchForm/SearchForm.js
src/components/shared/SearchForm/SearchButton.js
src/components/shared/SearchForm/SearchForm.js
src/components/shared/SearchForm/SearchForm.scss
src/styles/main.scss

Online resources proto  lf cleanup

---

.tugboat/config.yml

Fix for Tugboat Config to Allow Base Previews

---

package-lock.json
src/apollo/client/queries/OnlineResourceById.gql
src/apollo/server/resolvers/searchResolver.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.module.css
src/components/online-resources/SearchResults/SearchDocumentQuery.gql
src/components/online-resources/SearchResults/SearchResults.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2174)
[Preview Env](https://pr142-0qhyqyxjkkbw7g0l0rt6jw4cm8il50ys.tugboat.qa/research/collections/online-resources/search?alpha=all)
-

RENO-2174: Online Resources: Build OnlineResourceCard Component

---

src/components/ds-prototypes/CardGrid/CardGridSkeleton.js
src/components/ds-prototypes/CardGrid/CardGridSkeleton.scss
src/components/online-resources/MostPopularResources/MostPopularResources.js
src/components/online-resources/ResourceTopics/ResourceTopics.js
src/components/online-resources/SearchResults/SearchResults.js
src/components/online-resources/SearchResults/SearchResultsSkeleton.js
src/components/online-resources/SearchResults/SearchResultsSkeleton.scss
src/styles/main.scss

[Jira Ticket](https://jira.nypl.org/browse/RENO-2236)
- Adds a CardGridSkeleton loader to replace the Skeleton loader in ResourceTopics and MostPopularResources components

RENO-2236+RENO-2239: Online Resources: Card Grid & Search Results Skeleton Loaders

---

src/apollo/server/resolvers/onlineResourceResolver.js
src/components/ds-prototypes/AutoSuggest/AutoSuggest.scss
src/components/ds-prototypes/Card/Card.js
src/components/ds-prototypes/CardGrid/CardGrid.scss
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.module.css
src/components/online-resources/SearchResults/SearchResults.js
src/components/online-resources/SearchResults/SearchResults.module.css
src/components/online-resources/VerifyForm/VerifyForm.module.css
src/components/shared/layouts/PageContainer.js
src/styles/ds-overrides.scss

Online Resources: VQA Fixes

---

src/components/online-resources/SidebarMenus/content.js

RENO-2346: Update Sidebar Links

---

src/apollo/server/datasources/DrupalApi.js
src/components/ds-prototypes/MultiSelect/MultiSelect.js
src/components/ds-prototypes/MultiSelect/MultiSelect.module.css
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
src/components/online-resources/SearchForm/MultiSelect.js
src/components/online-resources/SearchForm/SearchFilters.js
testHelper/__mocks/availabilityFilterMock.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2353)
- Changes "Availability" filter to use radios instead of checkboxes
- Small adjustments for MultiSelect styles from VQA feedback
- Small copy updates for "Availability" filter names

RENO-2353: Change Availability Filters to Radios Instead of Checkboxes

---

src/components/ds-prototypes/FilterBar/FilterBar.js
src/components/ds-prototypes/FilterBar/FilterBar.module.css
src/components/online-resources/AlphabetNav/AlphabetNav.js
src/components/online-resources/AlphabetNav/AlphabetNav.module.css
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2329)
- Fixes Multiple ID issue on Search Results and Online Resource Card
- Changes "Filter By" from H3 to H2
- Removes Button from AlphabetNav and just uses anchor links

RENO-2329: Accessibility QA Fixes

---

src/apollo/server/datasources/DrupalApi.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2355)
-

RENO-2355: Drupal Page Cache Causes 304 Not Modified Errors

---

src/components/online-resources/SearchResults/SearchResults.js
src/components/online-resources/SearchResults/SearchResultsDetails.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2347)
- Adjusts calculation to the results message `startItem` number when the number of items on the page is less than the per page limit
- Adds a conditional around the Pagination to only display when there are items returned

RENO-2347 Search results message adjustments

---

src/apollo/server/datasources/DrupalApi.js
src/apollo/server/resolvers/searchResolver.js

testing diff logic for availability filters and status badge?

---

src/components/online-resources/SearchResults/SearchResults.js

debug to add client ip to search results

---

src/apollo/server/resolvers/ipAccessCheckResolver.js
src/apollo/server/resolvers/searchResolver.js
src/components/online-resources/SearchResults/SearchResults.js
src/components/shared/layouts/AppLayout.js
src/utils/getRequestIp.js
src/utils/getRequestIp.test.js

Different approach for getting ip address

---

src/components/online-resources/SearchForm/SearchFilters.js

RENO-2393: Set audience by age to be limited by only online resource nodes

---

src/apollo/server/resolvers/searchResolver.js
src/components/ds-prototypes/MultiSelect/MultiSelect.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.module.css

[Jira Ticket](https://jira.nypl.org/browse/RENO-2397)
-

RENO-2397: Add All Branch Libraries to Access Locations Links

---

src/components/ds-prototypes/MultiSelect/MultiSelect.js
src/components/ds-prototypes/MultiSelect/MultiSelect.module.css
src/styles/ds-overrides.scss

Vqa tweaks 2021 08 05

---

src/apollo/server/datasources/DrupalApi.js

RENO-2413: Added encodeURIComponent to SQ Before ending to drupal api

---

src/components/location-finder/SearchFilters/SearchFilters.scss

[Jira Ticket](https://jira.nypl.org/browse/RENO-2400)
- DS Checkbox component had some upstream changes - CSS adjustment to account for this

RENO-2400: Minor css adjustment to account for DS Checkbox change

---

src/components/online-resources/MostPopularResources/MostPopularResources.js
src/components/online-resources/SearchResults/SearchResults.js
src/pages/research/collections/articles-databases/[slug].js

RENO-2422: Change most popular resources heading text

---

src/apollo/server/resolvers/searchResolver.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCardHeading.js

Temporary Fix for Authentication Type API Change

---

CHANGELOG.md
src/apollo/server/resolvers/searchResolver.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCardHeading.js

RENO-2433: Wire up api changes for authentication type

---

src/components/online-resources/SearchForm/SearchFilters.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-2336)
-

RENO-2336: Bug fix for multiselect items not being selectable after unselected

---

cypress/support/utils.ts
cypress/tests/locations/request-visit.test.js
src/components/locations/RequestVisitForm/FormFields/HoneypotFormField.tsx
src/components/locations/RequestVisitForm/RequestVisitConfirmation.tsx
src/components/locations/RequestVisitForm/RequestVisitForm.tsx
src/components/locations/RequestVisitForm/RequestVisitFormError.tsx
src/context/FormContext.tsx

- Fixes typo on confirmation pg, "received" was spelled wrong.
- Remove headphone and icon component from confirmation pg link 
- Adds honeypot hidden form field to prevent spam email submissions.
- Updates tests

RENO-2212: VQA Fixes

---

src/components/locations/RequestVisitForm/PageContainer.js
src/styles/ds-overrides.scss

temp fix for red color

---

src/components/locations/RequestVisitForm/FormFields/VisitTypeFormField.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-2467)
- Adds "Reader Advisory" checkbox to Virtual Visit options

RENO-2467: Add Reader Advisory Checkbox option

---

cypress/support/utils.ts
cypress/tests/locations/request-visit.test.js
src/components/locations/RequestVisitForm/FormFields/LibraryFormField.tsx
src/components/locations/RequestVisitForm/FormFields/OrgFormField.tsx
src/pages/locations/request-visit/index.tsx

RENO-2569: Form Copy Changes

---

cypress/tests/blogs/blog-post-routes.test.js
src/apollo/client/queries/DecoupledRouter.gql
src/apollo/server/datasources/DrupalApi.js
src/apollo/server/resolvers/decoupledRouterResolver.js
src/apollo/server/type-defs/decoupledRouter.js
src/components/shared/layouts/AppLayout.js
src/hooks/useDecoupledRouterQuery.ts
src/pages/blogs/[slug].tsx
src/pages/research/collections/articles-databases/featured/[slug].js

RENO-2552: Fix Drupal Redirects for Blogs

---

src/__content/blogs.js
src/apollo/client/fragments/blogFields.js
src/apollo/server/resolvers/utils.js
src/apollo/server/type-defs/shared.js
src/components/shared/ContentComponents/ImageComponent.tsx
src/components/shared/Image/ImageTypes.ts

[Jira Ticket](https://jira.nypl.org/browse/RENO-2661)
-

RENO-2661: Wire Up Link Fields for Images

---

src/components/ds-prototypes/Menu/Menu.module.css
src/components/ds-prototypes/Menu/Menu.tsx
src/components/ds-prototypes/Menu/MenuItem.tsx
src/components/locations/RequestVisitForm/PageContainer.js
src/components/online-resources/layouts/PageContainer.js
src/pages/locations/index.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-2829)
- Adds breadcrumb title to `/locations/request-visit` pg
- Fixes heading level for sidebar menu to set h3
- Fixes heading level for bottom rail menu on `research/collections/articles-databases`
- Fixes responsiveness of bottom rail menu on `research/collections/articles-databases` and `/locations`

RENO-2836: Fixes for pageContainer and menus

---

src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
src/hooks/useOembedApi.ts
src/pages/api/oembed.js

RENO-2856: Libsyn Podcast Doesn't Render on Frontend

---

CHANGELOG.md
src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts

[Jira Ticket](https://jira.nypl.org/browse/RENO-2839)
-

RENO-2839: Add Support for Livestream Video Embed

---

src/components/home-v1/CardGrid.tsx
src/components/home-v1/ComponentWrapper.tsx
src/components/home-v1/SlideShow/SlideShow.tsx
src/components/home-v1/SlideShow/SlideShowButton.tsx
src/components/home-v1/SlideShow/SlideShowContainer.tsx
src/components/home-v1/SlideShow/SlideShowTypes.ts
src/components/home-v1/SlideShow/useSlideShow.ts
src/components/home-v1/mockContent.js
src/components/home-v1/theme/index.tsx
src/pages/index.tsx
src/pages/locations/index.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-2854)
- build out Prototype of SlideShow on homepage
- updated ComponentWrapper Props

Slider component

---

src/components/home-v1/CardGrid/Card.tsx
src/components/home-v1/ComponentWrapper.tsx
src/components/home-v1/Hero.tsx
src/components/home-v1/SlideShow/SlideShow.tsx
src/components/home-v1/SlideShow/SlideShowButton.tsx
src/components/home-v1/StaffPicks/StaffPick.tsx
src/components/home-v1/mockContent.js
src/components/home-v1/theme/card.tsx
src/components/home-v1/theme/cardGrid.tsx
src/components/home-v1/theme/hero.tsx
src/components/home-v1/theme/index.tsx
src/pages/index.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-2510)
- adds responsive design for Hero component
- fixes button issue on mobile on SlideShow component
- fixes mobile view for blog component 
- updates top padding on componentWrapper
- fix grid gap in the chakra style files (replace grid with gridGap)

RENO-2510: Update Hero Component, add Layout Tweaks

---

Dockerfile

Re-roll of this PR: https://github.com/NYPL/dxp-react-search/pull/281 -- but with only the remaining changes to `Dockerfile` not already on development.
- Addressing Nginx vulnerability with updating container's Nginx version

Updated Dockerfile (Bill)

---

next.config.js
src/apollo/server/resolvers/searchResolver.js
src/apollo/server/resolvers/utils/resolveImage.ts
src/components/blogs/BlogCollection/BlogCard.tsx

RENO-2947: fix placement of key in Blogcards location list

---

src/styles/base/_print.scss
src/styles/main.scss

[Jira Ticket](https://jira.nypl.org/browse/RENO-2678)
- Adds a new sass partial stylesheet that targets print via media query
- Hides header, footer, navigation and asides
- Expands hrefs to display underlying links on printed page

RENO-2678: Print Styles

---

.vercel/build.sh
src/apollo/server/resolvers/homePageResolver.js
src/apollo/server/type-defs/homepage.js
src/components/home-v1/CardGrid/Card.tsx
src/components/home-v1/CardGrid/CardGrid.tsx
src/components/home-v1/EventCollection/EventCard.tsx
src/components/home-v1/EventCollection/EventCollection.tsx
src/components/home-v1/EventCollection/EventCollectionTabPanelContent.tsx
src/components/home-v1/theme/card.tsx
src/components/home-v1/theme/event.ts
src/components/home-v1/theme/index.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3070)
- Fixes layout/ style of "What's on" section
- Adds style theme file for "What's on" section (event.ts)
- Cleans up of unused code in EventCollection folder
- Removes `featured` key from event query
- Removes event related variant props from Card.tsx and CardGrid.tsx
- Removes event related styles from card.tsx

RENO-3070: Whats On Code Cleanup

---

src/components/home-v1/EventCollection/EventCollection.tsx
src/components/home-v1/Hero/HeroWithData.tsx
src/components/home-v1/HomePage/HomePage.tsx
src/components/home-v1/HomePage/index.tsx
src/components/home-v1/Spotlight/Spotlight.tsx
src/pages/home-preview.tsx
src/pages/index.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3080)
- Updates homepage to use getStaticProps

RENO-3080: Update Home Page To Use getStaticProps

---

src/components/home-v1/CardGrid/Card.test.tsx
src/components/home-v1/CardGrid/CardGrid.test.tsx
src/components/home-v1/CardGrid/__snapshots__/Card.test.tsx.snap
src/components/home-v1/CardGrid/__snapshots__/CardGrid.test.tsx.snap

[Jira Ticket](https://jira.nypl.org/browse/RENO-3090)
- Fixes CardGrid and Card component tests

RENO-3090/Fix Failing CardGrid Tests

---

next.config.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-3098)
- Updates `next.config.js` with custom build id.

RENO-3098: Add Custom Build ID for RP Rules

---

src/__content/homePage.ts
src/components/home-v1/HomePage/HomePage.tsx
src/components/shared/Meta/Meta.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3148)
- Adds meta tags for home page.

RENO-3148: Add homepage meta tags

---

src/components/home-v1/Hero/Hero.tsx
src/components/home-v1/theme/hero.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3172)
- Updates Hero component to render a h1 heading
- Updates the hero style file to apply heading style to the new h1

RENO-3172: Update Hero Heading

---

src/components/home-v1/theme/hero.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3200)
- Adds minWidth for Hero text box

RENO-3200: Fix Hero Text Box for Tablet

---

src/components/home-v1/Hero/Hero.tsx
src/components/home-v1/theme/hero.tsx
src/components/home-v1/theme/index.tsx

RENO-3199: Hero Background Image Large Screens Fix

---

src/components/press-releases/PressRelease/PressRelease.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3068)
- Removed the date from the individual page

RENO-3068: Update Individual PressRelease UX

---

src/components/shared/EmailSubscription/EmailSubscriptionConfirmation.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3387)
- Adds an Error message to the Subscription Confirmation 
&emsp; - Send to: "enews@nypl.org" 
&emsp; - Subject: "Please re-activate my e-mail address"

RENO-3387: Add Error Message

---

src/components/shared/EmailSubscription/EmailSubscriptionConfirmation.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3397)
-

RENO-3397: Manage Focus Upon Confirmation Message Render

---

src/components/shared/EmailSubscription/EmailSubscriptionForm.tsx
src/components/shared/EmailSubscription/EmailSubscriptionWrapper.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3394)
- Adds Label to from input field
- Updates Submit button design
- Updates wrapper to align with Figma design

RENO-3394: Update EmailSubscriptionForm With Final Design

---

.github/PULL_REQUEST_TEMPLATE.md

[Jira Ticket](https://jira.nypl.org/browse/RENO-3436)
- Updates the Github PR template

RENO-3436: Update Github PR Template

---

CHANGELOG.md
src/apollo/server/resolvers/utils/resolveDrupalParagraphs.ts
src/apollo/server/type-defs/sectionFront.js
src/apollo/server/type-defs/shared.js
src/components/section-fronts/SectionFrontPage/SectionFrontPage.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-XXXX)
[Figma Design](https://www.figma.com/file/XXX)
-

RENO-3482: Wire up text paragraph component for section fronts

---

CHANGELOG.md
src/components/press-releases/PressReleaseCollection/PressReleaseCollection.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3496)
- Fixes issue where using pagination returns an error.

RENO-3496: Fixes pagination bug

---

CHANGELOG.md
src/components/shared/ButtonLink/ButtonLink.tsx
src/components/shared/CardGrid/Card.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3592)

RENO-3592: Adjust size of app store download buttons

---

src/components/shared/DonorCredit/DonorCredit.test.tsx
src/components/shared/DonorCredit/DonorCredit.tsx
src/components/shared/DonorCredit/__snapshots__/DonorCredit.test.tsx.snap

[Jira Ticket](https://jira.nypl.org/browse/RENO-3591)
-

RENO-3591: Donor Credit Allow Line Break

---

CHANGELOG.md
src/apollo/with-drupal-router.test.js
src/apollo/with-drupal-router.ts

[Jira Ticket](https://jira.nypl.org/browse/RENO-3633)
- Properly convert multilevel slug from array to url path
- Adds test coverage

RENO-3633: with-drupal-router Can't Resolve Multilevel Path

---

src/styles/base/_base.scss

[Jira Ticket](https://jira.nypl.org/browse/RENO-XXXX)
[Figma Design](https://www.figma.com/file/XXX)
-

RENO-3684: Update Header Placeholder Height

---

package-lock.json
package.json
src/apollo/server/datasources/LocalistApi.ts
src/apollo/server/resolvers/index.js
src/apollo/server/resolvers/localistEventsResolver.ts
src/apollo/server/resolvers/localistFilterResolver.ts
src/apollo/server/type-defs/event.js
src/components/ds-prototypes/MultiSelect/MultiSelect.tsx
src/components/events/EventCollection.tsx
src/components/events/EventDetails.tsx
src/components/events/EventSearchResult.tsx
src/components/events/SearchForm/SearchForm.tsx
src/components/events/index.ts
src/components/events/layout/PageContainer.tsx
src/components/shared/FilterBar/FilterBar.tsx
src/components/shared/FilterBar/MultiSelect.tsx
src/components/shared/FilterBar/types.ts
src/pages/events/[...slug].tsx
src/pages/events/calendar.tsx
src/pages/events/calendar/search.tsx
src/utils/config.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-3680)
- Adds a search page
- Adds a localist query for search terms and places
- Adds localist search query 
- Updates FilterBar and MultiSelect to allow a combined onSubmit

RENO-3680: Add Events Filters

---

next.config.js
src/components/blogs/BlogCollection/BlogCard.tsx

fixes for RENO-3331 + RENO-3727

RENO-3331+3727: Small Fixes for D9 Blog Changes

---

src/components/shared/DrupalParagraphs/DrupalParagraphs.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3747)
- Update DrupalParagraphs component to handle content of type object *not* array)
** Disclaimer: Due to the updated DS Components the last Breadcrumbs item is now also a link, one cypress test will fail

RENO-3747:  Update DrupalParagraphs

---

src/apollo/server/resolvers/drupal-paragraphs/index.ts
src/apollo/server/resolvers/drupal-paragraphs/slideshow-resolver.ts
src/apollo/server/resolvers/page-resolver.ts
src/apollo/server/type-defs/page.ts
src/components/pages/Page.tsx
src/components/shared/ContentComponents/ButtonLinks.tsx
src/components/shared/ContentComponents/SocialEmbed.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3749)
- Connects all available Drupal paragraphs to Page resolver
- Updates Page type in schema with availabale Drupal Paragraph types
- Update Page.tsx to query and render all available paragraphs

RENO-3749: Connect Drupal Paragraphs to Page Resolver

---

next.config.js
src/__content/blogs.js

[Jira Ticket](https://jira.nypl.org/browse/RENO-3731)
- Change default language for blog channel
- Update next.config.js to allow images from qa-drupal.nypl.org

RENO-3731: New Blog Channel Description

---

src/components/home-v1/CardGrid/Card.tsx
src/components/home-v1/CardGrid/__snapshots__/CardGrid.test.tsx.snap

[Jira Ticket](https://jira.nypl.org/browse/RENO-3737)
*I made this a Draft PR because I am wondering if it would be better to remove bold and italic options from the card text options in Drupal.* 
- Remove DS `Text` component for card description and pass the description to the Chakra `Box` component through `dangerouslySetInnerHTML` prop
- pass the `Box` component the `as='p"` prop to ensure the description text is rendered in a paragraph html tag

RENO-37373: Update Homepage Card

---

src/components/shared/DonorCredit/__snapshots__/DonorCredit.test.tsx.snap
src/components/shared/TextFormatted/TextFormatted.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3816)
- Updates the css for link text to match new DS styling
- Updates the css for `h3`, `h4` tag to math the new DS styling
- Updates Snapshot tests

RENO-3816: Update TextFormattet component CSS

---

.env.example
provisioning/set-env

[Jira Ticket](https://jira.nypl.org/browse/RENO-3853)
[Docs showing the ENV variable to disable telemetry](https://nextjs.org/telemetry#what-is-being-collected)
- Adds .env variable to disable next/vercel telemetry

RENO-3853: Disable Next/Vercel Telemetry

---

CHANGELOG.md
src/components/shared/ContentComponents/CardList.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-XXXX)
[Figma Design](https://www.figma.com/file/XXX)
- Removes style applied to first `p` tag on CardList description

Blog CardList fix

---

CHANGELOG.md
src/components/shared/ContentComponents/CardList.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-XXXX)
[Figma Design](https://www.figma.com/file/XXX)
-

Blog Card List: Heading Links

---

CHANGELOG.md
src/components/online-resources/AlphabetNav/AlphabetNav.js
src/components/online-resources/OnlineResourceCard/OnlineResourceCard.js
src/components/press-releases/PressReleaseCollection/PressReleaseCard.tsx
src/components/shared/Card/Card.tsx

[Jira Ticket](https://jira.nypl.org/browse/RENO-3970)
-

RENO-3970: Remove Next Link & Router Push
